### ISSUE TITLE
[Request] Clicking on Logged in Character 

### ISSUE THREAD

**Issue by pritch1** [EVE-KILL/Issues#16]
**Is your feature request related to a problem? Please describe.**
Feature request.

**Describe the solution you'd like**
When clicking on your logged in Character it would be nice if it loaded up your own kill information, so you have a shortcut to this rather than searching.

**Describe alternatives you've considered**

**Additional context**
Loading recent kill and a main home page is nice and where the default should be imo.

**Comment by KongGal** [comment]
Would a link in the menu there with "My Character" be fine?

**Comment by pritch1** [comment]
Whatever works and looks natural to be honest. Without over populating the quick links

**Comment by karbowiak** [comment]
fixed: https://github.com/EVE-KILL/Frontend/commit/7a796ca5fafafe3aa79b81b69c3eb6fb87dad881
