### ISSUE TITLE
[Request] STOMP Endpoint for Ship Group ID/Ship ID

### ISSUE THREAD

**Issue by entropylaw** [EVE-KILL/Issues#22]
**/topic/shipGroup/{shipGroupId}**
- example: `/topic/shipGroup/900` would be to track all marauders

**/topic/ship/{shipId}**
- example: `/top/ship/17478` would be just Retriever.

**Comment by karbowiak** [comment]
Fixed https://github.com/EVE-KILL/Killboard/commit/ec532cbc49d2a61fa6637361f6cb19cd92bc057a
