### ISSUE TITLE
Website Kill filters either do not apply correctly or once applied, start to feed in general kills instead of only the filter selected

### ISSUE THREAD

**Issue by Madman045** [EVE-KILL/Issues#32]
**Describe the bug**

When selecting a Kill filter, the page either sometimes does not load the filter entirely, or it does filter it, but then normal kills start  being added to the list you are looking at

**To Reproduce**
![Kill filters](https://github.com/user-attachments/assets/79293276-e014-4483-b94c-bb9c769e2349)

I selected w-space for example - https://eve-kill.com/kills/wspace?killlistPage=1

Leave it for 30 seconds and then other system kills start filtering in, see attached image.

**Expected behavior**

The kill filters should only show what is selected, i have also tried T3 ships and it showed all ship types.

**Screenshots**

**Desktop (please complete the following information):**
 - Chrome Version 128.0.6613.120 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by karbowiak** [comment]
This has been fixed, a whole bunch of more topics were added to rabbitmq, and killlist listens to them on the extra kills pages.
