### ISSUE TITLE
[Enhancement] Vector based search.

### ISSUE THREAD

**Issue by SolsticeProjekt** [EVE-KILL/Issues#5]
I'll give a relatable example in words, to make it easily understandable.

"Find all solo kills around the star in Hek, within 1 million km"

That way you can find all the 1vs1 around the star.
Not just at the warp-in, but *around the star.*

This would automagically work  for everything that has coordinates, (aka everything)
including planets, moons, belts, gates, stations,
and probably makes locationID pretty much useless.

It's 2024! Vector based searches are the hype!

Thank you!

**Comment by karbowiak** [comment]
This has been implemented using the 

https://eve-kill.com/docs/apidocs#tag/killmail/GET/api/killmail/near/%7Bsystem_id%7D/%7BdistanceInMeters%7D/%7Bx%7D/%7By%7D/%7Bz%7D/%7Bdays%7D

and 

https://eve-kill.com/docs/apidocs#tag/killmail/GET/api/killmail/near/%7Bcelestial_id%7D/%7BdistanceInMeters%7D/%7Bdays%7D

API endpoints :)
